### ISSUE TITLE
Bug: Open File with which Program Keeps Popping Up

### ISSUE THREAD

**Issue by deathtothenig** [RooVetGit/Roo-Code#87]
### Which API Provider are you using?

Anthropic

### Which Model are you using?

Claude 3.5 Sonnet

### What happened?

In Windows, whenever you try to save an edit to a file, the popup asking for which program to use to open a certain file type opens up. It's constantly happening every time you get to the point where you save an edit to a file. It doesn't happen in the regular Cline extension only this forked version of it, Roo Cline. Is everyone else using Linux or am I the only person who exists, because there is no way someone else hasn't noticed this which makes the extension almost unusable.

### Steps to reproduce

1. Ask to do anything which requires editing a file
2. Once it's done and it gets to the save button it shows the popup in Windows asking which program to use to open the file
3. It happens with or without the auto write features enabled

**Comment by mrubens** [comment]
Which version are you on? That should be fixed in 2.1.13 and later.

**Comment by ryanjoachim** [comment]
As someone exclusively running on Windows, I haven't seen this behavior related to editing files since I started using Roo in v2.1.14. 
That being said, back when the sound effects were first introduced I _**did**_ run into this every time Roo played a sound - but only because I did not have a default handler for `.wav` files.

@deathtothenig what file type is the popup trying to open? The quickest and simplest fix for your specific case is to:
1. Select `Visual Studio Code` (or w/e it's named in the popup)
2. Then click on the `Always` button (which sets VSCode as the default handler for that file type)

**Comment by deathtothenig** [comment]
> Which version are you on? That should be fixed in 2.1.13 and later.

I think I was using 2.1.6. Now I'm using 2.2 and it still does it. I disabled all auto-approve to get a better idea of when it does it and it happens literally every time the save button appears after Cline wants to edit a file: or the approve button appears after it says Cline wants to read a file:. It happens every time. I'm using VS Cod 1.95.3. It's not usable like this.

**Comment by mrubens** [comment]
> > Which version are you on? That should be fixed in 2.1.13 and later.
> 
> I think I was using 2.1.6. Now I'm using 2.2 and it still does it. I disabled all auto-approve to get a better idea of when it does it and it happens literally every time the save button appears after Cline wants to edit a file: or the approve button appears after it says Cline wants to read a file:. It happens every time. I'm using VS Cod 1.95.3. It's not usable like this.

Can you try turning the sound checkbox on and then back off, hitting done, and then starting a new chat?

**Comment by deathtothenig** [comment]
I'm trying to figure out how to get it working. So far this change below has stopped the, "What program to open this file type with," when sound effects is enabled. But it still doesn't play any sounds like the celebration.wav etc. when it should.

In sound.ts, change:

From:
```
		const player = require("play-sound")()
		player.play(filepath, function (err: any) {
			if (err) {
				throw new Error("Failed to play sound effect")
			}
		})
```

To:
```
		// Extract the audio type from the filepath
		const audioType = filepath.split('/').pop()?.split('.')[0]
		if (!audioType) {
			throw new Error("Invalid audio file path")
		}

		// Get the active Cline instance
		const vscode = require('vscode')
		const ClineProvider = vscode.extensions.getExtension('rooveterinaryinc.roo-cline')?.exports?.ClineProvider
		const activeInstance = ClineProvider?.getVisibleInstance()
		
		if (activeInstance?.view?.webview) {
			// Use the existing webview message system to play audio
			activeInstance.postMessageToWebview({
				type: "playSound",
				audioType: audioType
			})
		}
```

**Comment by mrubens** [comment]
Turns out there are a bunch of [issues](https://github.com/shime/play-sound/issues) with play-sound on Windows. Maybe https://www.npmjs.com/package/sound-play is better?

**Comment by mrubens** [comment]
We released a new version with the sound-play library. Should be fixed now - can you reopen if not? Thank you!
